name = "SpeedMapping"
uuid = "f1835b91-879b-4a3f-a438-e4baacf14412"
authors = ["Nicolas Lepage-Saucier <42039487+nicolasLepageSaucier@users.noreply.github.com> and contributors"]
version = "0.4.1"

[deps]
ForwardDiff = "f6369f11-2688-5a93-a128-0538d151201e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6"
ForwardDiff = "0.10"
Reexport = "1.0"
StaticArrays = "1.0"
# This is the critical line. 


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
